In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.sectorperformance import SectorPerformances
from config import akey

In [2]:
from alpha_vantage.cryptocurrencies import CryptoCurrencies
import matplotlib.pyplot as plt
cc = CryptoCurrencies(key=akey, output_format='pandas')
coins = ['ETH','DOGE']
data, meta_data = cc.get_digital_currency_daily(symbol='BTC', market='EUR')
data['Currency'] = 'BTC'
data.to_csv('data/crypto_daily_prices.csv')
for coin in coins:
    try:
        data, meta_data = cc.get_digital_currency_daily(symbol=coin, market='EUR')
        data['Currency'] = coin
        data.to_csv('data/crypto_daily_prices.csv', mode='a', header=False)
        time.sleep(2.5)
        print(f'{coin} data found. Appending to CSV')
    except:
        print(f'{coin} not available. No data added.')
        pass
print(f'Data Done')

ETH data found. Appending to CSV
DOGE data found. Appending to CSV
Data Done

In [4]:
data, meta_data = cc.get_digital_currency_weekly(symbol='BTC', market='EUR')
data['Currency'] = 'BTC'
data.to_csv('data/crypto_weekly_prices.csv')
for coin in coins:
    try:
        data, meta_data = cc.get_digital_currency_weekly(symbol=coin, market='EUR')
        data['Currency'] = coin
        data.to_csv('data/crypto_weekly_prices.csv', mode='a', header=False)
        time.sleep(2.5)
        print(f'{coin} data found. Appending to CSV')
    except:
        print(f'{coin} not available. No data added.')
        pass
print(f'Data Done')

ETH data found. Appending to CSV
DOGE data found. Appending to CSV
Data Done

In [5]:
data, meta_data = cc.get_digital_currency_monthly(symbol='BTC', market='EUR')
data['Currency'] = 'BTC'
data.to_csv('data/crypto_monthly_prices.csv')
for coin in coins:
    try:
        data, meta_data = cc.get_digital_currency_monthly(symbol=coin, market='EUR')
        data['Currency'] = coin
        data.to_csv('data/crypto_monthly_prices.csv', mode='a', header=False)
        time.sleep(2.5)
        print(f'{coin} data found. Appending to CSV')
    except:
        print(f'{coin} not available. No data added.')
        pass
print(f'Data Done')

ETH data found. Appending to CSV
DOGE not available. No data added.
Data Done

In [34]:
daily_crypto = pd.read_csv('data/crypto_daily_prices.csv')
daily_crypto['date'] =  pd.to_datetime(daily_crypto['date'])
daily_crypto.head()

,date,1a. open (EUR),1b. open (USD),2a. high (EUR),2b. high (USD),3a. low (EUR),3b. low (USD),4a. close (EUR),4b. close (USD),5. volume,6. market cap (USD),Currency
0,2021-04-17,51196.165907,61334.81,51534.411388,61740.04,51011.972658,61114.14,51154.898339,61285.37,1992.888167,1992.888167,BTC
1,2021-04-16,52718.600278,63158.74,53020.653167,63520.61,50082.000000,60000.00,51196.157560,61334.80,91764.139884,91764.139884,BTC
2,2021-04-15,52552.319691,62959.53,53253.860000,63800.00,51768.094000,62020.00,52719.635306,63159.98,51649.700340,51649.700340,BTC
3,2021-04-14,53066.060847,63575.01,54133.633800,64854.00,51167.944700,61301.00,52552.319691,62959.53,82616.343993,82616.343993,BTC
4,2021-04-13,49965.150347,59860.01,53235.304619,63777.77,49919.358705,59805.15,53066.052500,63575.00,82848.688746,82848.688746,BTC

In [40]:
daily_crypto.columns

Index(['date', '1a. open (EUR)', '1b. open (USD)', '2a. high (EUR)',
       '2b. high (USD)', '3a. low (EUR)', '3b. low (USD)', '4a. close (EUR)',
       '4b. close (USD)', '5. volume', '6. market cap (USD)', 'Currency'],
      dtype='object')

In [75]:
us_crypto = daily_crypto.drop(['1a. open (EUR)', '2a. high (EUR)', '3a. low (EUR)','4a. close (EUR)'], axis=1)
us_crypto.columns = ['Date','Open','High','Low','Close','Volume','Market Cap','Coin']
us_crypto.head()

,Date,Open,High,Low,Close,Volume,Market Cap,Coin
0,2021-04-17,61334.81,61740.04,61114.14,61285.37,1992.888167,1992.888167,BTC
1,2021-04-16,63158.74,63520.61,60000.00,61334.80,91764.139884,91764.139884,BTC
2,2021-04-15,62959.53,63800.00,62020.00,63159.98,51649.700340,51649.700340,BTC
3,2021-04-14,63575.01,64854.00,61301.00,62959.53,82616.343993,82616.343993,BTC
4,2021-04-13,59860.01,63777.77,59805.15,63575.00,82848.688746,82848.688746,BTC

In [76]:
us_crypto['Date'] =  pd.to_datetime(us_crypto['Date'])

In [77]:
us_crypto['200_MA'] = us_crypto['Close'].rolling(window=200).mean()
us_crypto['150_MA'] = us_crypto['Close'].rolling(window=150).mean()
us_crypto['50_MA'] = us_crypto['Close'].rolling(window=50).mean()
us_crypto['Volatility']=(us_crypto['High']-us_crypto['Low'])/us_crypto['Open']
us_crypto.set_index(['Coin'], inplace=True)
us_crypto.head()

,Date,Open,High,Low,Close,Volume,Market Cap,200_MA,150_MA,50_MA,Volatility
Coin,,,,,,,,,,,
BTC,2021-04-17,61334.81,61740.04,61114.14,61285.37,1992.888167,1992.888167,NaN,NaN,NaN,0.010205
BTC,2021-04-16,63158.74,63520.61,60000.00,61334.80,91764.139884,91764.139884,NaN,NaN,NaN,0.055742
BTC,2021-04-15,62959.53,63800.00,62020.00,63159.98,51649.700340,51649.700340,NaN,NaN,NaN,0.028272
BTC,2021-04-14,63575.01,64854.00,61301.00,62959.53,82616.343993,82616.343993,NaN,NaN,NaN,0.055887
BTC,2021-04-13,59860.01,63777.77,59805.15,63575.00,82848.688746,82848.688746,NaN,NaN,NaN,0.066365

In [78]:
btc_df = us_crypto.loc['BTC']
eth_df = us_crypto.loc['ETH']
doge_df = us_crypto.loc['DOGE']
doge_df.head()

,Date,Open,High,Low,Close,Volume,Market Cap,200_MA,150_MA,50_MA,Volatility
Coin,,,,,,,,,,,
DOGE,2021-04-17,0.365385,0.381250,0.333927,0.355900,2.025452e+09,2.025452e+09,202.374329,228.734506,326.685718,0.129514
DOGE,2021-04-16,0.182500,0.450000,0.179100,0.365443,5.751055e+10,5.751055e+10,201.853657,228.067676,322.776827,1.484381
DOGE,2021-04-15,0.121432,0.191892,0.119788,0.182360,2.461597e+10,2.461597e+10,201.318219,227.442091,318.846274,0.593785
DOGE,2021-04-14,0.094401,0.145395,0.092118,0.121433,3.668099e+10,3.668099e+10,200.780426,226.878434,314.544303,0.564374
DOGE,2021-04-13,0.070700,0.096226,0.070641,0.094402,1.360584e+10,1.360584e+10,200.244098,226.320664,309.952191,0.361875

In [79]:
doge_df.reset_index(inplace=True)
doge_df.set_index('Date', inplace=True)

In [81]:
btc_df.to_csv('data/btc_data.csv')
eth_df.to_csv('data/eth_data.csv')
doge_df.to_csv('data/doge_data.csv')